default_stages:
  - commit
exclude: node_modules|.git|.tox
fail_fast: true
repos:
  - hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1

  - hooks:
      - id: isort
        entry: isort
    repo: https://github.com/pycqa/isort
    rev: 5.10.1

  - hooks:
      - exclude: (/settings/)
        id: black
        language_version: python3.8
        require_serial: true
        types:
          - python
    repo: https://github.com/ambv/black
    rev: 21.12b0

#  - hooks:
#    - id: pylint
#      exclude: "[a-zA-Z]*/(migrations)/(.)*|marscalonyapi|manage.py"
#    repo: https://github.com/pycqa/pylint
#    rev: v2.12.2
